apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume1
  labels:
    type: local
spec:
  storageClassName: jenkins-storageclass
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/jenkins"
