apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim1
spec:
  storageClassName: jenkins-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Mi
